"on":
  push:
    branches:
    - dockerfile
name: Deploy to test-new-cli
jobs:
  porter-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set Github tag
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Deploy stack
      timeout-minutes: 30
      uses: porter-dev/porter-cli-action-testing@v0.2.4
      with:
        command: apply -f ./porter.yaml
      env:
        PORTER_CLUSTER: "1"
        PORTER_HOST: https://decent-garfish-gorgeous.ngrok-free.app
        PORTER_PROJECT: "1"
        PORTER_STACK_NAME: test-new-cli
        PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
        PORTER_TOKEN: ${{ secrets.PORTER_STACK_1_1 }}
