
        
on:
  push:
    branches:
    - test
name: Deploy to porter_stack_test-2
jobs:
  porter-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set Github tag
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Install Porter
      timeout-minutes: 30
      run: /bin/bash -c "$(curl -fsSL https://install.porter.run)"
    - name: Login
      timeout-minutes: 30
      run: porter auth login --token $PORTER_TOKEN
      env:
        PORTER_CLUSTER: 2
        PORTER_HOST: https://aebf-160-72-72-58.ngrok-free.app
        PORTER_PROJECT: 1
        PORTER_STACK_NAME: pls-work-1
        PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
        PORTER_TOKEN: ${{ secrets.PORTER_STACK_1_2 }}
    - name: Deploy stack
      timeout-minutes: 30
      run: porter apply
      env:
        PORTER_CLUSTER: 2
        PORTER_HOST: https://aebf-160-72-72-58.ngrok-free.app
        PORTER_PROJECT: 1
        PORTER_STACK_NAME: test-2
        PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
        PORTER_TOKEN: ${{ secrets.PORTER_STACK_1_2 }}
